//! Mathematical operation codes used by the intermediate representation.

use super::node::TensorValue;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Opcode {
    Add,
    Sub,
    Mul,
    Div,
    MatMul,
    Conv2d,
    Relu,
    Gelu,
    Silu,
    Sigmoid,
    Tanh,
    Exp,
    Log,
    Sqrt,
    Neg,
    Abs,
    LeakyRelu,
    Elu,
    Softplus,
    Hardswish,
    Clamp,
    Sign,
    Round,
    Maximum,
    Minimum,
    LogicalNot,
    Reshape,
    Transpose,
    Concat,
    Slice,
    Flatten,
    Squeeze,
    Unsqueeze,
    ReduceSum,
    ReduceMean,
    ReduceMax,
    LogSoftmax,
    MaxPool,
    AvgPool,
    BatchNorm,
    LayerNorm,
    Softmax,
    BiasAdd,
    Pad,
    Gather,
    ScatterNd,
    Constant(TensorValue),
    Input,
    Conv1d,
    Conv3d,
    ConvTranspose2d,
    Prelu,
    RMSNorm,
    Embedding,
    Pow,
    GtScalar,
    LtScalar,
    EqScalar,
    AddScalar,
    ArgMax,
    MulScalar,
    DivScalar,
    /// Mish activation: x * tanh(softplus(x)).
    Mish,
    UpsampleNearest2d,
    UpsampleBilinear2d,
    AdaptiveAvgPool2d,
    Repeat,
    CumSum,
    Erf,
    Flip,
    /// Element-wise where(condition, x, y).
    Where,
    /// Fused Top-K producing values and indices.
    TopK,
    Shape,
    Cast,
    Quantize,
    Dequantize,
    ToF16,
    ToF32,
    QuantizeActivations,
    DequantizeActivations,
    Expand,
    Tile,
    Range,
    SgdUpdate,
    AdamUpdate,
    AdamWUpdate,
    MuonUpdate,
    LionUpdate,
    RmspropUpdate,
    GradientScale,
    QuantizeGradient,
    DequantizeGradient,
    FusedResidualAddNorm,
}
